name: Test Workflow

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  build-job:
    runs-on: ubuntu-latest

    steps:
    - name: Build Step
      run: echo "This is the test build job echo step."

  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test Step
      run: echo "This is the test test job echo step."

  deploy-job:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Step
      run: echo "This is the test deploy echo step."
